version: 0.0
os: linux
files:
  - source: maven-app/sample.war
    destination: /opt/
hooks:
  BeforeInstall:
    - location: stop_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_tomcat.sh
      timeout: 300
      runas: root
