version: 0.0
os: linux
files:
  - source: sample.war
    destination: /opt/tomcat
hooks:
  ApplicationStop:
    - location: stop_tomcat.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: stop_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_tomcat.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: stop_tomcat.sh
      timeout: 300
      runas: root
